version: '3.8'

services:
  auth-app:
    container_name: auth-app
    image: auth-app:latest
    build:
      context: .
      dockerfile: auth/src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/authdb
      - QUARKUS_DATASOURCE_USERNAME=authuser
      - QUARKUS_DATASOURCE_PASSWORD=authpassword
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=update
    depends_on:
      - db

  db:
    container_name: db-auth-dm
    image: postgres:15
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./auth/src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: