server.port=8081
server.servlet.context-path=/api
spring.datasource.url=jdbc:mariadb://localhost:3306/dm-users-db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

## JWT Configuration ##
jwt.secret = 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
jwt.expiration = 36000000