version: '3.7'

services:
  cart-db:
    image: mongo:latest
    container_name: mongo
    restart: always
    command: --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  carts-q:
    container_name: carts-q
    build:
#      context: .
#      dockerfile: Dockerfile.jvm
      context: ../../  # This should be the path to your root project folder where 'src' is located
      dockerfile: σρ/main/docker/Dockerfile.jvm  # Path to Dockerfile relative to the context
    environment:
      QUARKUS_MONGODB_CONNECTION_STRING: mongodb://admin:secret@mongodb:27017/mydatabase?authSource=admin
      JAVA_OPTS_APPEND: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus.mongodb.connection-string=mongodb://admin:secret@mongodb:27017/mydatabase?authSource=admin"
    ports:
      - "8088:8080"
    depends_on:
      - cart-db

volumes:
  mongodb_data:
